[project]
repository-type = "library"
versioning-scheme = "library"
branching-model = "library-release"
release-model = "artifact-publishing"
primary-language = "python"

[ci]
versions = ["3.12", "3.13", "3.14"]
integration-tests = true

[publish]
release = true
docs = true

[dependencies]
vergil = "v2.1"
