"""Precompiled mapping data for MQSC <-> snake_case translations."""

from __future__ import annotations

MAPPING_DATA: dict[str, object] = {'commands': {'ALTER AUTHINFO': {'qualifier': 'authinfo',
                                 'status': 'provisional'},
              'ALTER BUFFPOOL': {'qualifier': 'buffpool',
                                 'status': 'provisional'},
              'ALTER CFSTRUCT': {'qualifier': 'cfstruct',
                                 'status': 'provisional'},
              'ALTER CHANNEL': {'qualifier': 'channel',
                                'status': 'provisional'},
              'ALTER COMMINFO': {'qualifier': 'comminfo',
                                 'status': 'provisional'},
              'ALTER LISTENER': {'qualifier': 'listener',
                                 'status': 'provisional'},
              'ALTER NAMELIST': {'qualifier': 'namelist',
                                 'status': 'provisional'},
              'ALTER PROCESS': {'qualifier': 'process',
                                'status': 'provisional'},
              'ALTER PSID': {'qualifier': 'psid',
                             'status': 'provisional'},
              'ALTER QMGR': {'qualifier': 'qmgr',
                             'status': 'provisional'},
              'ALTER SECURITY': {'qualifier': 'security',
                                 'status': 'provisional'},
              'ALTER SERVICE': {'qualifier': 'service',
                                'status': 'provisional'},
              'ALTER SMDS': {'qualifier': 'smds',
                             'status': 'provisional'},
              'ALTER STGCLASS': {'qualifier': 'stgclass',
                                 'status': 'provisional'},
              'ALTER SUB': {'qualifier': 'sub',
                            'status': 'provisional'},
              'ALTER TOPIC': {'qualifier': 'topic',
                              'status': 'provisional'},
              'ALTER TRACE': {'qualifier': 'trace',
                              'status': 'provisional'},
              'ARCHIVE LOG': {'qualifier': 'log',
                              'status': 'no-equivalent'},
              'BACKUP CFSTRUCT': {'qualifier': 'cfstruct',
                                  'status': 'no-equivalent'},
              'CLEAR QLOCAL': {'qualifier': 'queue',
                               'status': 'provisional'},
              'CLEAR TOPICSTR': {'qualifier': 'topicstr',
                                 'status': 'provisional'},
              'DEFINE AUTHINFO': {'qualifier': 'authinfo',
                                  'status': 'provisional'},
              'DEFINE BUFFPOOL': {'qualifier': 'buffpool',
                                  'status': 'provisional'},
              'DEFINE CFSTRUCT': {'qualifier': 'cfstruct',
                                  'status': 'provisional'},
              'DEFINE CHANNEL': {'qualifier': 'channel',
                                 'status': 'provisional'},
              'DEFINE COMMINFO': {'qualifier': 'comminfo',
                                  'status': 'provisional'},
              'DEFINE LISTENER': {'qualifier': 'listener',
                                  'status': 'provisional'},
              'DEFINE LOG': {'qualifier': 'log',
                             'status': 'provisional'},
              'DEFINE MAXSMSGS': {'qualifier': 'maxsmsgs',
                                  'status': 'provisional'},
              'DEFINE NAMELIST': {'qualifier': 'namelist',
                                  'status': 'provisional'},
              'DEFINE PROCESS': {'qualifier': 'process',
                                 'status': 'provisional'},
              'DEFINE PSID': {'qualifier': 'psid',
                              'status': 'provisional'},
              'DEFINE SERVICE': {'qualifier': 'service',
                                 'status': 'provisional'},
              'DEFINE STGCLASS': {'qualifier': 'stgclass',
                                  'status': 'provisional'},
              'DEFINE SUB': {'qualifier': 'sub',
                             'status': 'provisional'},
              'DEFINE TOPIC': {'qualifier': 'topic',
                               'status': 'provisional'},
              'DELETE AUTHINFO': {'qualifier': 'authinfo',
                                  'status': 'provisional'},
              'DELETE AUTHREC': {'qualifier': 'authrec',
                                 'status': 'provisional'},
              'DELETE BUFFPOOL': {'qualifier': 'buffpool',
                                  'status': 'provisional'},
              'DELETE CFSTRUCT': {'qualifier': 'cfstruct',
                                  'status': 'provisional'},
              'DELETE CHANNEL': {'qualifier': 'channel',
                                 'status': 'provisional'},
              'DELETE COMMINFO': {'qualifier': 'comminfo',
                                  'status': 'provisional'},
              'DELETE LISTENER': {'qualifier': 'listener',
                                  'status': 'provisional'},
              'DELETE NAMELIST': {'qualifier': 'namelist',
                                  'status': 'provisional'},
              'DELETE POLICY': {'qualifier': 'policy',
                                'status': 'provisional'},
              'DELETE PROCESS': {'qualifier': 'process',
                                 'status': 'provisional'},
              'DELETE PSID': {'qualifier': 'psid',
                              'status': 'provisional'},
              'DELETE SERVICE': {'qualifier': 'service',
                                 'status': 'provisional'},
              'DELETE STGCLASS': {'qualifier': 'stgclass',
                                  'status': 'provisional'},
              'DELETE SUB': {'qualifier': 'sub',
                             'status': 'provisional'},
              'DELETE TOPIC': {'qualifier': 'topic',
                               'status': 'provisional'},
              'DISPLAY APSTATUS': {'qualifier': 'apstatus',
                                   'status': 'provisional'},
              'DISPLAY ARCHIVE': {'qualifier': 'archive',
                                  'status': 'provisional'},
              'DISPLAY AUTHINFO': {'qualifier': 'authinfo',
                                   'status': 'provisional'},
              'DISPLAY AUTHREC': {'qualifier': 'authrec',
                                  'status': 'provisional'},
              'DISPLAY AUTHSERV': {'qualifier': 'authserv',
                                   'status': 'provisional'},
              'DISPLAY CFSTATUS': {'qualifier': 'cfstatus',
                                   'status': 'provisional'},
              'DISPLAY CFSTRUCT': {'qualifier': 'cfstruct',
                                   'status': 'provisional'},
              'DISPLAY CHANNEL': {'qualifier': 'channel',
                                  'status': 'provisional'},
              'DISPLAY CHINIT': {'qualifier': 'chinit',
                                 'status': 'provisional'},
              'DISPLAY CHLAUTH': {'qualifier': 'channel',
                                  'status': 'provisional'},
              'DISPLAY CHSTATUS': {'qualifier': 'channel',
                                   'status': 'provisional'},
              'DISPLAY CLUSQMGR': {'qualifier': 'clusqmgr',
                                   'status': 'provisional'},
              'DISPLAY CMDSERV': {'qualifier': 'cmdserv',
                                  'status': 'provisional'},
              'DISPLAY COMMINFO': {'qualifier': 'comminfo',
                                   'status': 'provisional'},
              'DISPLAY CONN': {'qualifier': 'conn',
                               'status': 'provisional'},
              'DISPLAY ENTAUTH': {'qualifier': 'entauth',
                                  'status': 'provisional'},
              'DISPLAY GROUP': {'qualifier': 'group',
                                'status': 'provisional'},
              'DISPLAY LISTENER': {'qualifier': 'listener',
                                   'status': 'provisional'},
              'DISPLAY LOG': {'qualifier': 'log',
                              'status': 'provisional'},
              'DISPLAY LSSTATUS': {'qualifier': 'lsstatus',
                                   'status': 'provisional'},
              'DISPLAY MAXSMSGS': {'qualifier': 'maxsmsgs',
                                   'status': 'provisional'},
              'DISPLAY NAMELIST': {'qualifier': 'namelist',
                                   'status': 'provisional'},
              'DISPLAY POLICY': {'qualifier': 'policy',
                                 'status': 'provisional'},
              'DISPLAY PROCESS': {'qualifier': 'process',
                                  'status': 'provisional'},
              'DISPLAY PUBSUB': {'qualifier': 'pubsub',
                                 'status': 'provisional'},
              'DISPLAY QMGR': {'qualifier': 'qmgr',
                               'status': 'provisional'},
              'DISPLAY QMSTATUS': {'qualifier': 'qmgr',
                                   'status': 'provisional'},
              'DISPLAY QSTATUS': {'qualifier': 'queue',
                                  'status': 'provisional'},
              'DISPLAY QUEUE': {'qualifier': 'queue',
                                'status': 'provisional'},
              'DISPLAY SBSTATUS': {'qualifier': 'sbstatus',
                                   'status': 'provisional'},
              'DISPLAY SECURITY': {'qualifier': 'security',
                                   'status': 'provisional'},
              'DISPLAY SERVICE': {'qualifier': 'service',
                                  'status': 'provisional'},
              'DISPLAY SMDS': {'qualifier': 'smds',
                               'status': 'provisional'},
              'DISPLAY SMDSCONN': {'qualifier': 'smdsconn',
                                   'status': 'provisional'},
              'DISPLAY STGCLASS': {'qualifier': 'stgclass',
                                   'status': 'provisional'},
              'DISPLAY SUB': {'qualifier': 'sub',
                              'status': 'provisional'},
              'DISPLAY SVSTATUS': {'qualifier': 'svstatus',
                                   'status': 'provisional'},
              'DISPLAY SYSTEM': {'qualifier': 'system',
                                 'status': 'provisional'},
              'DISPLAY TCLUSTER': {'qualifier': 'tcluster',
                                   'status': 'provisional'},
              'DISPLAY THREAD': {'qualifier': 'thread',
                                 'status': 'provisional'},
              'DISPLAY TOPIC': {'qualifier': 'topic',
                                'status': 'provisional'},
              'DISPLAY TPSTATUS': {'qualifier': 'tpstatus',
                                   'status': 'provisional'},
              'DISPLAY TRACE': {'qualifier': 'trace',
                                'status': 'provisional'},
              'DISPLAY USAGE': {'qualifier': 'usage',
                                'status': 'provisional'},
              'MOVE QLOCAL': {'qualifier': 'queue',
                              'status': 'no-equivalent'},
              'PING CHANNEL': {'qualifier': 'channel',
                               'status': 'provisional'},
              'PING QMGR': {'qualifier': 'qmgr',
                            'status': 'provisional'},
              'PURGE CHANNEL': {'qualifier': 'channel',
                                'status': 'no-equivalent'},
              'RECOVER BSDS': {'qualifier': 'bsds',
                               'status': 'no-equivalent'},
              'RECOVER CFSTRUCT': {'qualifier': 'cfstruct',
                                   'status': 'no-equivalent'},
              'REFRESH CLUSTER': {'qualifier': 'cluster',
                                  'status': 'provisional'},
              'REFRESH QMGR': {'qualifier': 'qmgr',
                               'status': 'provisional'},
              'REFRESH SECURITY': {'qualifier': 'security',
                                   'status': 'provisional'},
              'RESET CFSTRUCT': {'qualifier': 'cfstruct',
                                 'status': 'provisional'},
              'RESET CHANNEL': {'qualifier': 'channel',
                                'status': 'provisional'},
              'RESET CLUSTER': {'qualifier': 'cluster',
                                'status': 'provisional'},
              'RESET QMGR': {'qualifier': 'qmgr',
                             'status': 'provisional'},
              'RESET QSTATS': {'qualifier': 'queue',
                               'status': 'provisional'},
              'RESET SMDS': {'qualifier': 'smds',
                             'status': 'provisional'},
              'RESET TPIPE': {'qualifier': 'tpipe',
                              'status': 'provisional'},
              'RESOLVE CHANNEL': {'qualifier': 'channel',
                                  'status': 'provisional'},
              'RESOLVE INDOUBT': {'qualifier': 'indoubt',
                                  'status': 'provisional'},
              'RESUME QMGR': {'qualifier': 'qmgr',
                              'status': 'provisional'},
              'RVERIFY SECURITY': {'qualifier': 'security',
                                   'status': 'no-equivalent'},
              'SET ARCHIVE': {'qualifier': 'archive',
                              'status': 'provisional'},
              'SET AUTHREC': {'qualifier': 'authrec',
                              'status': 'provisional'},
              'SET CHLAUTH': {'qualifier': 'channel',
                              'status': 'provisional'},
              'SET LOG': {'qualifier': 'log',
                          'status': 'provisional'},
              'SET POLICY': {'qualifier': 'policy',
                             'status': 'provisional'},
              'SET SYSTEM': {'qualifier': 'system',
                             'status': 'provisional'},
              'START CHANNEL': {'qualifier': 'channel',
                                'status': 'provisional'},
              'START CHINIT': {'qualifier': 'chinit',
                               'status': 'provisional'},
              'START CMDSERV': {'qualifier': 'cmdserv',
                                'status': 'provisional'},
              'START LISTENER': {'qualifier': 'listener',
                                 'status': 'provisional'},
              'START QMGR': {'qualifier': 'qmgr',
                             'status': 'provisional'},
              'START SERVICE': {'qualifier': 'service',
                                'status': 'provisional'},
              'START SMDSCONN': {'qualifier': 'smdsconn',
                                 'status': 'provisional'},
              'START TRACE': {'qualifier': 'trace',
                              'status': 'provisional'},
              'STOP CHANNEL': {'qualifier': 'channel',
                               'status': 'provisional'},
              'STOP CHINIT': {'qualifier': 'chinit',
                              'status': 'provisional'},
              'STOP CMDSERV': {'qualifier': 'cmdserv',
                               'status': 'provisional'},
              'STOP CONN': {'qualifier': 'conn',
                            'status': 'provisional'},
              'STOP LISTENER': {'qualifier': 'listener',
                                'status': 'provisional'},
              'STOP QMGR': {'qualifier': 'qmgr',
                            'status': 'provisional'},
              'STOP SERVICE': {'qualifier': 'service',
                               'status': 'provisional'},
              'STOP SMDSCONN': {'qualifier': 'smdsconn',
                                'status': 'provisional'},
              'STOP TRACE': {'qualifier': 'trace',
                             'status': 'provisional'},
              'SUSPEND QMGR': {'qualifier': 'qmgr',
                               'status': 'provisional'}},
 'qualifiers': {'apstatus': {'request_key_map': {},
                             'request_value_map': {},
                             'response_key_map': {},
                             'response_value_map': {}},
                'archive': {'request_key_map': {},
                            'request_value_map': {},
                            'response_key_map': {},
                            'response_value_map': {}},
                'authinfo': {'request_key_map': {'classuser': 'CLASSUSR',
                                                 'short_user': 'SHORTUSR',
                                                 'user_field': 'USRFIELD'},
                             'request_value_map': {},
                             'response_key_map': {'CLASSUSR': 'classuser',
                                                  'SHORTUSR': 'short_user',
                                                  'USRFIELD': 'user_field'},
                             'response_value_map': {}},
                'authrec': {'request_key_map': {},
                            'request_value_map': {},
                            'response_key_map': {},
                            'response_value_map': {}},
                'authserv': {'request_key_map': {},
                             'request_value_map': {},
                             'response_key_map': {},
                             'response_value_map': {}},
                'bsds': {'request_key_map': {},
                         'request_value_map': {},
                         'response_key_map': {},
                         'response_value_map': {}},
                'buffpool': {'request_key_map': {},
                             'request_value_map': {},
                             'response_key_map': {},
                             'response_value_map': {}},
                'cfstatus': {'request_key_map': {},
                             'request_value_map': {},
                             'response_key_map': {},
                             'response_value_map': {}},
                'cfstruct': {'request_key_map': {},
                             'request_value_map': {},
                             'response_key_map': {},
                             'response_value_map': {}},
                'channel': {'request_key_map': {'channel_type': 'CHLTYPE',
                                                'batch_heartbeat': 'BATCHHB',
                                                'batch_interval': 'BATCHINT',
                                                'batch_size': 'BATCHSZ',
                                                'disc_interval': 'DISCINT',
                                                'mca_name': 'MCANAME',
                                                'mca_type': 'MCATYPE',
                                                'mode_name': 'MODENAME',
                                                'msg_exit': 'MSGEXIT',
                                                'password': 'PASSWORD',
                                                'reset_seq': 'RESETSEQ',
                                                'send_exit': 'SENDEXIT',
                                                'tp_name': 'TPNAME',
                                                'use_dlq': 'USEDLQ'},
                            'request_value_map': {},
                            'response_key_map': {'CHLTYPE': 'channel_type',
                                                 'BATCHHB': 'batch_heartbeat',
                                                 'BATCHINT': 'batch_interval',
                                                 'BATCHSZ': 'batch_size',
                                                 'DISCINT': 'disc_interval',
                                                 'MCANAME': 'mca_name',
                                                 'MCATYPE': 'mca_type',
                                                 'MODENAME': 'mode_name',
                                                 'MSGEXIT': 'msg_exit',
                                                 'PASSWORD': 'password',
                                                 'RESETSEQ': 'reset_seq',
                                                 'SENDEXIT': 'send_exit',
                                                 'TPNAME': 'tp_name',
                                                 'USEDLQ': 'use_dlq'},
                            'response_value_map': {}},
                'chlauth': {'request_key_map': {},
                            'request_value_map': {},
                            'response_key_map': {},
                            'response_value_map': {}},
                'chinit': {'request_key_map': {},
                           'request_value_map': {},
                           'response_key_map': {},
                           'response_value_map': {}},
                'clusqmgr': {'request_key_map': {},
                             'request_value_map': {},
                             'response_key_map': {},
                             'response_value_map': {}},
                'cluster': {'request_key_map': {},
                            'request_value_map': {},
                            'response_key_map': {},
                            'response_value_map': {}},
                'cmdserv': {'request_key_map': {},
                            'request_value_map': {},
                            'response_key_map': {},
                            'response_value_map': {}},
                'comminfo': {'request_key_map': {},
                             'request_value_map': {},
                             'response_key_map': {},
                             'response_value_map': {}},
                'conn': {'request_key_map': {},
                         'request_value_map': {},
                         'response_key_map': {},
                         'response_value_map': {}},
                'entauth': {'request_key_map': {},
                            'request_value_map': {},
                            'response_key_map': {},
                            'response_value_map': {}},
                'group': {'request_key_map': {},
                          'request_value_map': {},
                          'response_key_map': {},
                          'response_value_map': {}},
                'indoubt': {'request_key_map': {},
                            'request_value_map': {},
                            'response_key_map': {},
                            'response_value_map': {}},
                'listener': {'request_key_map': {'adapter': 'ADAPTER',
                                                 'backlog': 'BACKLOG',
                                                 'commands': 'COMMANDS',
                                                 'local_name': 'LOCLNAME',
                                                 'port': 'PORT',
                                                 'sessions': 'SESSIONS',
                                                 'socket': 'SOCKET',
                                                 'tp_name': 'TPNAME'},
                             'request_value_map': {},
                             'response_key_map': {'ADAPTER': 'adapter',
                                                  'BACKLOG': 'backlog',
                                                  'COMMANDS': 'commands',
                                                  'LOCLNAME': 'local_name',
                                                  'PORT': 'port',
                                                  'SESSIONS': 'sessions',
                                                  'SOCKET': 'socket',
                                                  'TPNAME': 'tp_name'},
                             'response_value_map': {}},
                'log': {'request_key_map': {},
                        'request_value_map': {},
                        'response_key_map': {},
                        'response_value_map': {}},
                'lsstatus': {'request_key_map': {},
                             'request_value_map': {},
                             'response_key_map': {},
                             'response_value_map': {}},
                'maxsmsgs': {'request_key_map': {},
                             'request_value_map': {},
                             'response_key_map': {},
                             'response_value_map': {}},
                'namelist': {'request_key_map': {},
                             'request_value_map': {},
                             'response_key_map': {},
                             'response_value_map': {}},
                'policy': {'request_key_map': {},
                           'request_value_map': {},
                           'response_key_map': {},
                           'response_value_map': {}},
                'process': {'request_key_map': {},
                            'request_value_map': {},
                            'response_key_map': {},
                            'response_value_map': {}},
                'psid': {'request_key_map': {},
                         'request_value_map': {},
                         'response_key_map': {},
                         'response_value_map': {}},
                'pubsub': {'request_key_map': {},
                           'request_value_map': {},
                           'response_key_map': {},
                           'response_value_map': {}},
                'qmgr': {'request_key_map': {'qmgr_name': 'QMNAME',
                                             'force': 'FORCE',
                                             'otel_trace': 'OTELTRAC'},
                         'request_value_map': {},
                         'response_key_map': {'QMNAME': 'qmgr_name',
                                              'FORCE': 'force',
                                              'OTELTRAC': 'otel_trace'},
                         'response_value_map': {}},
                'queue': {'request_key_map': {'current_q_depth': 'CURDEPTH',
                                              'def_persistence': 'DEFPSIST',
                                              'cap_expiry': 'CAPEXPRY',
                                              'clwl_use_q': 'CLWLUSEQ',
                                              'custom': 'CUSTOM',
                                              'def_bind': 'DEFBIND',
                                              'index_type': 'INDXTYPE',
                                              'max_q_depth': 'MAXDEPTH',
                                              'otel_trace': 'OTELTRAC',
                                              'q_type': 'QTYPE',
                                              'scope': 'SCOPE',
                                              'stream_q': 'STREAMQ',
                                              'usage': 'USAGE'},
                          'request_value_map': {'def_persistence': {'def': 'DEF',
                                                                    'not_fixed': 'NOTFIXED'}},
                          'response_key_map': {'CURDEPTH': 'current_q_depth',
                                               'DEFPSIST': 'def_persistence',
                                               'CAPEXPRY': 'cap_expiry',
                                               'CLWLUSEQ': 'clwl_use_q',
                                               'CUSTOM': 'custom',
                                               'DEFBIND': 'def_bind',
                                               'INDXTYPE': 'index_type',
                                               'MAXDEPTH': 'max_q_depth',
                                               'OTELTRAC': 'otel_trace',
                                               'QTYPE': 'q_type',
                                               'SCOPE': 'scope',
                                               'STREAMQ': 'stream_q',
                                               'USAGE': 'usage'},
                          'response_value_map': {'DEFPSIST': {'DEF': 'def',
                                                              'NOTFIXED': 'not_fixed'}}},
                'sbstatus': {'request_key_map': {},
                             'request_value_map': {},
                             'response_key_map': {},
                             'response_value_map': {}},
                'security': {'request_key_map': {},
                             'request_value_map': {},
                             'response_key_map': {},
                             'response_value_map': {}},
                'service': {'request_key_map': {'replace': 'REPLACE'},
                            'request_value_map': {},
                            'response_key_map': {'REPLACE': 'replace'},
                            'response_value_map': {}},
                'smds': {'request_key_map': {'ds_bufs': 'DSBUFS',
                                             'dsexpand': 'DSEXPAND',
                                             'smds': 'SMDS'},
                         'request_value_map': {},
                         'response_key_map': {'DSBUFS': 'ds_bufs',
                                              'DSEXPAND': 'dsexpand',
                                              'SMDS': 'smds'},
                         'response_value_map': {}},
                'smdsconn': {'request_key_map': {},
                             'request_value_map': {},
                             'response_key_map': {},
                             'response_value_map': {}},
                'stgclass': {'request_key_map': {},
                             'request_value_map': {},
                             'response_key_map': {},
                             'response_value_map': {}},
                'sub': {'request_key_map': {'sub_id': 'SUBID'},
                        'request_value_map': {},
                        'response_key_map': {},
                        'response_value_map': {}},
                'svstatus': {'request_key_map': {},
                             'request_value_map': {},
                             'response_key_map': {},
                             'response_value_map': {}},
                'system': {'request_key_map': {},
                           'request_value_map': {},
                           'response_key_map': {},
                           'response_value_map': {}},
                'tcluster': {'request_key_map': {},
                             'request_value_map': {},
                             'response_key_map': {},
                             'response_value_map': {}},
                'thread': {'request_key_map': {},
                           'request_value_map': {},
                           'response_key_map': {},
                           'response_value_map': {}},
                'topic': {'request_key_map': {'authrec': 'AUTHREC',
                                              'comm_info': 'COMMINFO',
                                              'custom': 'CUSTOM',
                                              'use_dlq': 'USEDLQ'},
                          'request_value_map': {},
                          'response_key_map': {'AUTHREC': 'authrec',
                                               'COMMINFO': 'comm_info',
                                               'CUSTOM': 'custom',
                                               'USEDLQ': 'use_dlq'},
                          'response_value_map': {}},
                'topicstr': {'request_key_map': {},
                             'request_value_map': {},
                             'response_key_map': {},
                             'response_value_map': {}},
                'tpipe': {'request_key_map': {},
                          'request_value_map': {},
                          'response_key_map': {},
                          'response_value_map': {}},
                'tpstatus': {'request_key_map': {},
                             'request_value_map': {},
                             'response_key_map': {},
                             'response_value_map': {}},
                'trace': {'request_key_map': {},
                          'request_value_map': {},
                          'response_key_map': {},
                          'response_value_map': {}},
                'usage': {'request_key_map': {},
                          'request_value_map': {},
                          'response_key_map': {},
                          'response_value_map': {}}},
 'version': 1}
